services:
  - type: web
    name: utah-pollinator-path
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
